name1 = input('enter a name ')
name2 = input('enter a name ')
name3 = input('enter a name ')
name4 = input('enter a name ')

print(name1 + ' ' + name2 + ' ' + name3 + ' ' + name4)
print(name1, name2, name3, name4)
print(f'{name1} {name2} {name3} {name4}')
names = []
names.append(name1)
names.append(name2)
names.append(name3)
names.append(name4)
print(names)
print(names[0])
print(names[1])
